<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>nfe-agendamento.ico</ApplicationIcon>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Version>0.1.30</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="Sigstore" Version="0.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="nfe-agendamento.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="RemoveUnusedWebView2WpfReference"
          BeforeTargets="ResolveAssemblyReferences"
          Condition="'$(UseWPF)' != 'true'">
    <ItemGroup>
      <Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" />
    </ItemGroup>
  </Target>
</Project>
